services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0
    ports:
      - "8545:8545"

  solana:
    image: solanalabs/solana:v1.18.15
    command: solana-test-validator --bind-address 0.0.0.0
    ports:
      - "8899:8899" # RPC
      - "8900:8900" # Websocket
      - "1024-1124:1024-1124/udp" # Dynamic ports

volumes:
  postgres_data:
