services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: ["anvil", "--host", "0.0.0.0"]
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "cast client --rpc-url http://localhost:8545 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  solana:
    image: solanalabs/solana:v1.18.15
    command: solana-test-validator --bind-address 0.0.0.0 --rpc-port 8899
    ports:
      - "8899:8899" # RPC
      - "8900:8900" # Websocket
      - "1024-1124:1024-1124/udp" # Dynamic ports
    healthcheck:
      test: ["CMD-SHELL", "solana cluster-version --url http://localhost:8899 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  postgres_data:
